name: Test quarto install on Linux
on: push

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: "Install quarto bin"
      run: |
        curl -s https://api.github.com/repos/quarto-dev/quarto-cli/releases/latest | 
        grep "browser_download_url.*deb" | 
        cut -d '"' -f 4 |
        wget -i -
        sudo dpkg -i quarto-0.1-amd64.deb
    - name: "Install Python Packages"
      run: |
        grep -iv "win" requirements.txt > TEMP_requirements.txt
        pip install -r TEMP_requirements.txt
        pip install jupyter
    - name: "Quarto env"
      run: |
        quarto env
    - name: "Quarto capabilities"
      run: |
        quarto capabilities
    - name: "Check Python installs"
      run: |
        echo "which python: $(which python)"
        echo "which python3: $(which python3)"
        echo "which jupyter: $(which jupyter)"
    - name: "NBConvert demo notebook"
      continue-on-error: true
      run: |
        jupyter nbconvert demo_notebook.ipynb --to pdf
    - name: "Check environment variables"
      continue-on-error: true
      run: |
        echo "${{ github.actions }}"
        if [ "${{ github.actions }}" = "true" ]; then echo "something"; else echo "else"; fi

    - name: "Quarto: Render sample Python"
      if: ${{ github.actions == 'true' }}
      run: |
        quarto render python_example.qmd --execute-debug --no-execute-daemon
