name: Test quarto install on Linux
on: push

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: "Install quarto bin"
      run: |
        curl -OL https://github.com/quarto-dev/quarto-cli/releases/download/v0.1.255/quarto-0.1-amd64.deb

        sudo dpkg -i quarto-0.1-amd64.deb
    - name: "Quarto env"
      run: |
        quarto env
    - name: "Quarto capabilities"
      run: |
        quarto capabilities
    - name: "Install Python Packages"
      run: |
        pip install -r requirements/common.txt
    - name: "Check Python installs"
      run: |
        echo "which python: $(which python)"
        echo "which python3: $(which python3)"
        echo "which jupyter: $(which jupyter)"
    - name: "Quarto: Render sample Python"
      run: |
        quarto render python_example.qmd
        #    - name: "Test commit"
        #      run: |
        #        git config --local user.name "$GITHUB_ACTOR"
        #        git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
        #        git add *.html
        #        git add *_files
        #        git commit -m 'Automated commit' || echo "No changes to commit"
        #        git push origin || echo "No changes to commit"
