name: Render quarto files
on: push

jobs:
  download:
    runs-on: ubuntu-latest
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
    - uses: actions/checkout@v2
    - name: "Install quarto bin"
      run: |
        #        curl -OL https://github.com/quarto-dev/quarto-cli/releases/download/v0.1.258/quarto-0.1-amd64.deb

        curl -s https://api.github.com/repos/quarto-dev/quarto-cli/releases/latest | 
        grep "browser_download_url.*deb" | 
        cut -d '"' -f 4 |
        wget -i -
        sudo dpkg -i quarto-0.1-amd64.deb
    - uses: actions/setup-python@v2
    - name: "Install Python deps"
      run: | 
        grep -iv "win" requirements.txt > TEMP_requirements.txt
        pip install -r TEMP_requirements.txt
    - name: "Check Python installation"
      run: |
        echo "which python: $(which python)"
        echo "which python3: $(which python3)"
        echo "which jupyter: $(which jupyter)"
    - uses: r-lib/actions/setup-r@v1
    - name: "Install R Packages: Cache packages"
      uses: actions/cache@v1
      with:
        path: ${{ env.RENV_PATHS_ROOT }}
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-
    - name: "Install R Packages: Restore packages"
      shell: Rscript {0}
      run: |
        if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
        renv::restore()
    - name: "Install reticulate"
      run: |
        Rscript -e "install.packages('remotes')"
        Rscript -e "remotes::install_github('rstudio/reticulate')"
    - name: "Quarto env"
      run: |
        quarto env
    - name: "Quarto capabilities"
      run: |
        quarto capabilities
    - name: "Render directory"
      run: |
        quarto render --execute-debug 
    - name: "Test commit"
      run: |
        git config --local user.name "$GITHUB_ACTOR"
        git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add docs/*
        git commit -m 'Automated commit' || echo "No changes to commit"
        git push origin || echo "No changes to commit"
